# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 \
--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableJetifier=true
kapt.use.worker.api=false